diffusion:
  target: ldm.models.diffusion.ldm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.012
    timesteps: 1000
   

model:
  target: ldm.modules.diffusionmodules.openaimodel.UNetModel
  params:
    image_size: [32, 48] # unused in the unet, but will be used when create xT
    in_channels: 4
    out_channels: 4
    model_channels: 320
    attention_resolutions: [ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_heads: 8
    transformer_depth: 1
    context_dim: 768
    fuser_type: gatedCA  #  cross attention for controlling condition
    use_checkpoint: True
    num_camera: 6

    controlling_condition_encoding:
      target: ldm.modules.diffusionmodules.controlling_condition_encoding.EncodingNet
      params:
        in_dim: 768 # this is pre-processing feature dim from CLIP Text encoder; penultimate feature  
        out_dim: 768


autoencoder:
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    scale_factor: 0.18215 
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: [128, 192]
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0


text_encoder:
  target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

convnext:
  target: ConvNeXt.convNeXt.ConvNeXt




train_dataset_names: 
  Nuscenes_with_path:
    max_boxes_per_sample: 80
    random_crop: False
    random_flip: True
val_dataset_names: 
  Nuscenes_with_path:
    max_boxes_per_sample: 80
    random_crop: False
    random_flip: False


controlling_condition_input:
  target: ldm.controlling_condition_input.controlling_condition_input.EncodingNetInput
  params: 
    img_size: [256, 384]